#!/bin/bash

if [ -f  ~/.config/i3/base_files/config_bindings.base ]; then
	cat ~/.config/i3/base_files/config_main.base > ~/.config/i3/config
	cat ~/.config/i3/base_files/config_bindings.base >> ~/.config/i3/config
else
	echo "Host not identified. Link config_bindings, touchpad.sh and keyboard.sh manually and rerun geni3config. Or stow apropiate packages"
fi
